@RadioModBackend_HostAddress = http://localhost:3045

POST {{RadioModBackend_HostAddress}}/search
Content-Type: application/json

{
  "searchString": "Ocean Man"
}

### Queue Endpoint

POST {{RadioModBackend_HostAddress}}/queue
Content-Type: application/json

{
  "videoId": "XJOex1-upLo",
  "videoTitle": "Ween - Ocean Man",
  "server": "Test Server",
  "playfabId": "testPlayfabId",
  "playerName": "TestPlayer",
  "serverWebhook": ""
}

### Playlist Endpoint

POST {{RadioModBackend_HostAddress}}/playlist
Content-Type: application/json
playlistId: PLi0mNC3SNQe129kBUp3Y6V50W52XBS97j